server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 172.16.252.111:8848
      username: nacos
      password: Nacos@4399
      config:
        namespace: linkcircle-cloud1
      discovery:
        namespace: linkcircle-cloud1
  config:
    import:
      - optional:nacos:gateway.yaml




