#server:
#  port: 17634
#  servlet:
#    context-path: /private-push
#  undertow:
#    buffer-size: 1024
#    threads:
#      io: 8
#      worker: 64
#    direct-buffers: true
#
#spring:
#  datasource:
#    url: jdbc:mysql://172.16.251.3:3300/private-number?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: cqt@1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      pool-name: MyHikariCP
#      minimum-idle: 30
#      idle-timeout: 600000
#      maximum-pool-size: 30
#      max-lifetime: 1800000
#      connection-timeout: 60000
#
#  redis:
#    password: cqt@1234
#    masterConnectionPoolSize: 500
#    cluster:
#      nodes:
#        - 172.16.251.47:9100
#        - 172.16.251.48:9100
#        - 172.16.251.49:9100
#    timeout: 5000
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#  rabbitmq:
#    publisher-returns: true
#    listener:
#      direct:
#        acknowledge-mode: manual
#        prefetch: 10
#        consumers-per-queue: 3
#      simple:
#        acknowledge-mode: manual
#        prefetch: 10
#        concurrency: 3
#    username: admin
#    password: cqt@1234
#    addresses: 172.16.251.91:5672
#    template:
#      #是否接收return消息的配置，true为接受confirm消息，默认为false
#      mandatory: false #延时队列开启则no_route，应关闭
#    virtual-host: fsbc
#    publisher-confirm-type: simple
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#    map-underscore-to-camel-case: true
#
#logging:
#  level:
#    com.alibaba.nacos: error
#
#private-push:
#  retryNum: 3     # 推送失败重推次数
#  retryMinute: 5   # 推送失败的重推时间  分钟