server:
  port: 5005
  servlet:
    context-path: /cloudcc-cdr-outside

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    enable-sql-runner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true

feign:
  httpclient:
    connection-timeout: 10000
    connection-timer-repeat: 10000

pzinfo:
  # 质检企业
  quality-company: 090008,090007,090014 
  # 睡眠时间 毫秒
  sleep: 1000
  push-num: 3
  sfkeysfdiscern: "E532ADC266440127B76DA10129CD6386"

xxljob:
  accessToken: 
  adminAddresses: http://172.16.251.223:8800/xxl-job-admin
  #adminAddresses: 
  logRetentionDays: 30
  logPath: /home/smp/xxl-job/${spring.application.name}
  address:
  ip: 
  port: 45002
  appName: ${spring.application.name}
  title: 呼叫中心-外部话单服务
  userName: admin
  password: cqt!010@Xxljob